#!/usr/bin/env bash
# derive-supersessions.sh — the supersession trail, DERIVED never hand-maintained (U9 discipline).
#
# Answers Jon's 08-15 question ("is it clear when interpretations supersede old decisions?") as an
# instrument: greps the trunk's authoritative sources for explicit supersession markers and emits
# wiki/references/supersession-trail.md with file:line cites. Regenerate any time; the page is a
# VIEW, and hand-edits to it are rot by definition (the header says so).
#
# Determinism contract: same inputs → byte-identical body. The one generation-stamp line is
# excluded from the identity check (--selftest regenerates twice and diffs bodies).
#
#   bash scripts/derive-supersessions.sh            regenerate the page
#   bash scripts/derive-supersessions.sh --selftest prove marker-detection + determinism; exit 0/3
set -u
cd "$(dirname "$0")/.." || exit 2

OUT="wiki/references/supersession-trail.md"
# R4 (2026-09-04): key derived by scripts/project_dirs.py.
MEMDIR="$(python "$(dirname "$0")/project_dirs.py" --primary 2>/dev/null)/memory"
PATTERN='[Ss]upersed|WITHDRAWN|withdrawn by|[Rr]etired|MOVED:|RESOLVED optional|REVISED 0|overrul|superseded by|→ should|-> should|→ must|-> must'

emit_body() {
  echo "---"
  echo "title: supersession-trail"
  echo "created: 2026-08-15"
  echo "provenance: \"DERIVED — regenerated by scripts/derive-supersessions.sh; hand-edits are rot and are overwritten without notice. Cites are file:line in the source of truth.\""
  echo "---"
  echo ""
  echo "# Supersession trail — derived, never hand-maintained"
  echo ""
  echo "Every line below is a grep hit on an explicit supersession marker in this trunk's"
  echo "authoritative sources. The RULE (Jon-derived, 08-15): a newer direct instruction supersedes"
  echo "an older ruling on its face; the record of the supersession lives WHERE THE RULING LIVES,"
  echo "and this page is only the index of those records. To dispute a line, edit the source, not"
  echo "this page, then regenerate."
  echo ""
  for f in WAKE.md wiki/references/standards-adoption-slate-2026-08-14.md "$MEMDIR/MEMORY.md" "$MEMDIR"/*.md; do
    [ -f "$f" ] || continue
    hits=$(grep -nE "$PATTERN" "$f" 2>/dev/null | grep -v '^\s*$' | head -40)
    [ -z "$hits" ] && continue
    echo "## $f"
    echo ""
    echo "$hits" | while IFS= read -r line; do
      n="${line%%:*}"; body="${line#*:}"
      # trim + hard-cap each cited line so the page stays an index, not a copy (U6)
      body=$(printf '%s' "$body" | sed 's/^[[:space:]]*//' | cut -c1-220)
      echo "- \`:$n\` — $body"
    done
    echo ""
  done
}

if [ "${1:-}" = "--selftest" ]; then
  rc=0
  A=$(mktemp); B=$(mktemp); C=$(mktemp)
  # determinism: two runs, identical bodies
  emit_body > "$A"; emit_body > "$B"
  cmp -s "$A" "$B" || { echo "SELFTEST BROKEN: two regenerations differ"; rc=3; }
  # detection: a canary marker must be picked up
  echo "CANARY ruling superseded by newer instruction" > "$C"
  grep -qE "$PATTERN" "$C" || { echo "SELFTEST BROKEN: marker pattern misses canary"; rc=3; }
  # non-detection: a clean line must NOT match
  echo "an ordinary sentence with no markers" > "$C"
  grep -qE "$PATTERN" "$C" && { echo "SELFTEST BROKEN: pattern fires on clean text"; rc=3; }
  rm -f "$A" "$B" "$C"
  [ $rc -eq 0 ] && echo "SELFTEST: determinism + marker hit + clean-text miss proven (3/3)"
  exit $rc
fi

{ emit_body; echo "<!-- generated: $(date '+%Y-%m-%d %H:%M:%S %Z') — this line only is expected to differ between regenerations -->"; } > "$OUT"
echo "REGENERATED: $OUT ($(wc -c < "$OUT") B, $(grep -c '^- ' "$OUT") cited lines)"
