#!/usr/bin/env python3
"""jon_words_coverage.py -- does the wiki hold what Jon actually typed?

WHY THIS EXISTS. Jon, 2026-09-04 08:49 CDT, verbatim (typos his):
  "i gave key context to CFL and Secretgary and Professionalism, and i am doubtful that CFL fully
   obsorbed all of it, i gave some of it to its bacground agents and i am doubtful that all logs
   are actully in the wiki as needed/intended."

That is a falsifiable claim and nothing in this repo could grade it. `scan_midturn_messages.py`
answers a NARROWER question (are subagent isMeta entries extracted at all) and reports a FAIL that
has stood for days without naming WHICH utterance is missing. This names them.

METHOD, stated so a reader can attack it:
  * POPULATION: every `*.jsonl` under ~/.claude/projects (ALL trunks -- CFL's instruments have
    historically searched CFL's roots and missed rulings typed to a sibling; CLAUDE.md's channel
    table row 4). Three entry classes carry Jon's typed words:
      (a) type=user with no isMeta            -- the ordinary turn
      (b) type=user with isMeta=true          -- mid-turn message to a SUBAGENT
      (c) type=attachment, attachment.type=queued_command -- typed WHILE a turn ran; the text is
          in `prompt`, and a compact can eat it before it ever becomes a turn
  * EXCLUSION is where this instrument can lie, so it is explicit and counted: harness furniture
    (task notifications, cross-session messages, system reminders, skill bodies, command output,
    hook feedback, compact summaries) is NOT Jon. Every exclusion rule is a substring/prefix listed
    in HARNESS_MARKERS and the count it removed is printed. A rule that removes everything would
    show as a near-zero population -- read POPULATION before reading COVERAGE.
  * COVERAGE: for each surviving utterance, take a distinctive probe -- the longest run of >=6
    words with no path/bracket punctuation -- and literal-grep the tracked wiki for it. A hit means
    the words reached the wiki. A miss means they did not, in that form.
    ⛔ This is the SAME test CLAUDE.md's emphasis rule demands of a quote: "THE TEST OF A QUOTE IS
    NOT WHETHER IT READS TRUE. IT IS WHETHER A LITERAL GREP OF IT RETURNS THE PRIMARY." So a
    paraphrase in the wiki counts as a MISS here, deliberately.
  * UNKNOWN dominates: an utterance too short to yield a 6-word probe is reported UNPROBEABLE, never
    as covered.

NOTHING IS WRITTEN except the report path given with --out. Read-only over JSONLs and the wiki.
"""
import argparse
import glob
import json
import os
import re
import subprocess
import sys

HARNESS_MARKERS = (
    "<local-command-stdout>",
    "IDLE BEAT",
    "[Cross-session idle notice]",
    "Gate floor (re-created",
    "<task-notification>",
    "<cross-session-message",
    "<system-reminder>",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]",
    "The coordinator sent a message while you were working:",
    "[Your previous response had no visible output",
    "[Request interrupted",
    "Caveat: The messages below were generated by the user while running local commands",
    "This session is being continued from a previous conversation",
    "Base directory for this skill:",
    "PRE-STOP CONSULT REQUIRED",
    "Gate floor (re-created",
    "<local-command-caveat>",
    "<command-name>",
    "POSTCOMPACT-STATUS:",
    "You are being consulted as an ELDER",
)
# A Jon turn is prose. These say "this is an agent report, not a person typing."
AGENT_REPORT_MARKERS = ("## Summary", "# Witness Report", "# Elder Report", "**Read scope:**",
                        "| id |", "```", "[measured", "[m 2026-")

PROBE_RE = re.compile(r"[A-Za-z][A-Za-z',.!?;:\- ]{20,}")


def text_of(d):
    if d.get("type") == "attachment":
        a = d.get("attachment", {}) or {}
        if a.get("type") == "queued_command":
            return a.get("prompt", "") or ""
        return ""
    m = d.get("message", {}) or {}
    c = m.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return " ".join(x.get("text", "") for x in c if isinstance(x, dict))
    return ""


def is_harness(t):
    head = t[:200]
    if any(h in head for h in HARNESS_MARKERS):
        return True
    if any(t.lstrip().startswith(m) for m in AGENT_REPORT_MARKERS):
        return True
    return False


def probe_of(t):
    """Longest clean word-run of >=6 words: the string we literal-grep for."""
    best = ""
    for m in PROBE_RE.finditer(t):
        s = m.group(0).strip()
        if len(s.split()) >= 6 and len(s) > len(best):
            best = s
    return best


def collect(projects_root, since):
    rows, excluded, short = [], 0, 0
    for f in glob.glob(os.path.join(projects_root, "**", "*.jsonl"), recursive=True):
        parts = f.split(os.sep)
        trunk = parts[-3] if "subagents" in f else parts[-2]
        venue = "subagent" if "subagents" in f else "main"
        try:
            fh = open(f, encoding="utf-8", errors="ignore")
        except OSError:
            continue
        with fh:
            for i, line in enumerate(fh, 1):
                if '"type":"user"' not in line and '"type": "user"' not in line \
                   and "queued_command" not in line:
                    continue
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                ts = (d.get("timestamp") or "")[:10]
                if since and ts and ts < since:
                    continue
                if d.get("type") not in ("user", "attachment"):
                    continue
                t = text_of(d)
                if not t or not t.strip():
                    continue
                # ⛔ STRUCTURAL RULE, added 2026-09-04 after the first run reported 793 missing and a
                # 14-row sample showed roughly two thirds of the population was NOT Jon. In a SUBAGENT
                # JSONL, a `type: user` entry is the PARENT'S DISPATCH BRIEF -- the coordinator's own
                # words, arriving in the user role because that is how a subagent is prompted. Only
                # `isMeta: true` entries there are a human typing mid-turn (CLAUDE.md channel row 2).
                # Without this rule the instrument grades CFL's own lane briefs as missing Jon quotes,
                # which is measuring the wrong population -- the exact defect this week keeps finding.
                if venue == "subagent" and not d.get("isMeta"):
                    excluded += 1
                    continue
                if is_harness(t):
                    excluded += 1
                    continue
                if len(t) > 4000:          # a person does not type 4 KB mid-turn
                    excluded += 1
                    continue
                p = probe_of(t)
                if not p:
                    short += 1
                    continue
                rows.append({"date": ts, "trunk": trunk, "venue": venue,
                             "file": os.path.basename(f), "line": i,
                             "bytes": len(t), "probe": p, "text": t.strip()})
    return rows, excluded, short


# ⛔ CAPTURE SINKS. A hit here means the words were DEPOSITED, not that any page uses them.
# Amendment proposed by soul (Claude Personal) 2026-09-04 and adopted the same hour, with their
# measured case: Jon's own cognition account sits in a raw arrivals dump, landed on no page, and a
# literal grep scores it COVERED. "Captured-but-never-landed needs to be its own bucket or your
# number will be optimistic in the direction nobody checks." So three buckets, never two.
CAPTURE_SINKS = ("intake-triage/agent-end", "skills-gate/probe-packets", "intake-triage/windows",
                 "jon-arrivals-raw", "intake-triage/rejected-pages", "intake-triage/cross-trunk-notes",
                 "JON-WORDS-COVERAGE", "session-stubs.md", "/log.md")


def wiki_hit(probe, wiki_root, exclude=()):
    """Literal grep of the tracked wiki.

    Returns (landed, captured_only_count):
      landed > 0        -- the words appear on an authored page
      landed 0, cap > 0 -- CAPTURED ONLY: deposited in a dump, used by nothing
      both 0            -- not in the wiki at all
      landed -1         -- UNKNOWN (grep failed); never read as 0
    """
    try:
        r = subprocess.run(["grep", "-rlF", "--", probe, wiki_root],
                           capture_output=True, text=True, timeout=120)
        files = [x.strip().replace("\\", "/") for x in r.stdout.splitlines() if x.strip()]
        # ⛔ SELF-CITATION. The report this run writes contains every probe verbatim, so on a re-run
        # each probe hits its own report and every MISSING row is promoted to CAPTURED-ONLY. Found
        # 2026-09-04 09:4x, before publishing, by asking why CAPTURED-ONLY was 527 of 646. A report
        # that makes its own subject look covered is a check that cannot fail.
        files = [f for f in files if not any(e and e in f for e in exclude)]
    except Exception:
        return -1, 0
    cap = [f for f in files if any(s in f for s in CAPTURE_SINKS)]
    return len(files) - len(cap), len(cap)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--projects", default=os.path.expanduser(r"~\.claude\projects"))
    ap.add_argument("--wiki", default="wiki")
    ap.add_argument("--since", default="2026-09-02")
    ap.add_argument("--out", help="write a markdown report here")
    ap.add_argument("--limit", type=int, default=0, help="probe only the first N (0 = all)")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()

    if a.selftest:
        return selftest()

    rows, excluded, short = collect(a.projects, a.since)
    rows.sort(key=lambda r: (r["date"], r["file"], r["line"]))
    if a.limit:
        rows = rows[: a.limit]

    print("POPULATION  candidate Jon utterances since %s : %d" % (a.since, len(rows)))
    print("            excluded as harness/agent-report  : %d" % excluded)
    print("            unprobeable (no 6-word run)       : %d   <- UNKNOWN, not covered" % short)

    self_paths = tuple(x for x in ((a.out or "").replace("\\", "/"),
                                    "JON-WORDS-COVERAGE") if x)
    landed = caponly = missing = unknown = 0
    for r in rows:
        L, C = wiki_hit(r["probe"], a.wiki, exclude=self_paths)
        r["landed"], r["cap"] = L, C
        if L < 0:
            r["bucket"] = "UNKNOWN"; unknown += 1
        elif L:
            r["bucket"] = "LANDED"; landed += 1
        elif C:
            r["bucket"] = "CAPTURED-ONLY"; caponly += 1
        else:
            r["bucket"] = "MISSING"; missing += 1

    print()
    print("COVERAGE    LANDED on an authored page       : %d" % landed)
    print("            CAPTURED-ONLY (dump, used by 0)  : %d   <- looks covered, is not" % caponly)
    print("            NOT in the wiki at all           : %d   <- THE NUMBER" % missing)
    print("            grep failed (UNKNOWN)            : %d" % unknown)
    print("IDENTITY    %d + %d + %d + %d = %d probed"
          % (landed, caponly, missing, unknown, len(rows)))
    print()
    print("BOUND, stated so this is not read as stronger than it is: a literal grep answers")
    print("  'do these words appear', NEVER 'was this directive absorbed'. A faithfully")
    print("  implemented paraphrase scores MISSING; an unused quote scores LANDED. (soul, 09-04)")

    if a.out:
        with open(a.out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("---\ntitle: \"Jon-words coverage -- which of his typed words reached the wiki\"\n")
            fh.write("kind: audit\nsince: %s\n" % a.since)
            fh.write("population: %d\nexcluded_harness: %d\nunprobeable: %d\n" % (len(rows), excluded, short))
            fh.write("landed: %d\ncaptured_only: %d\nmissing: %d\nunknown: %d\n---\n\n"
                     % (landed, caponly, missing, unknown))
            fh.write("Method and its bounds: see the module docstring of "
                     "`scripts/audit/jon_words_coverage.py`. A paraphrase in the wiki counts as a "
                     "MISS by design -- the test is a literal grep, per CLAUDE.md's quote rule.\n\n")
            for label in ("MISSING", "CAPTURED-ONLY", "LANDED", "UNKNOWN"):
                fh.write("\n## %s\n\n" % label)
                for r in rows:
                    if r["bucket"] != label:
                        continue
                    fh.write("- **%s | %s | %s:%d | %d B**\n  - probe: `%s`\n  - text: %s\n"
                             % (r["date"], r["trunk"], r["file"], r["line"], r["bytes"],
                                r["probe"][:120], r["text"][:600].replace("\n", " ")))
        print("wrote %s" % a.out)
    return 1 if missing else 0


def selftest():
    bad = 0
    cases = [
        ("harness task-notification excluded", is_harness("<task-notification>\nfoo") is True),
        ("harness cross-session excluded", is_harness('<cross-session-message from="x">') is True),
        ("coordinator relay excluded",
         is_harness("The coordinator sent a message while you were working: do x") is True),
        ("CONTROL: ordinary Jon prose is NOT harness",
         is_harness("i gave key context to CFL and Secretgary and Professionalism") is False),
        ("CONTROL: prose mentioning a task notification is NOT excluded (marker must lead)",
         is_harness("the task notification lied to me about the exit code") is False),
        # This case FAILED on its first run with a mis-specified expectation (`.split()[0] == "i"`,
        # asserting the probe would drop a leading "ok."). It does not, and should not: the contract
        # is a >=6-word run that is a literal substring of the input, so a grep of it can hit.
        # Corrected 2026-09-04 -- the test was wrong, the code was right; recorded rather than
        # quietly swapped, because a self-test edited to match the code is not a test.
        ("probe is a >=6-word literal substring of the input",
         (lambda s: (lambda p: len(p.split()) >= 6 and p in s)(probe_of(s)))
         ("ok. i am doubtful that all logs are actully in the wiki")),
        ("probe rejects a short line", probe_of("auto") == ""),
        ("CONTROL: a path-heavy line yields no probe",
         probe_of("N:/claude-cfl/clone/scripts/audit/x.py:12") == ""),
        ("queued_command text is read from prompt",
         text_of({"type": "attachment", "attachment": {"type": "queued_command",
                                                        "prompt": "hello there"}}) == "hello there"),
        ("user content list is joined",
         text_of({"type": "user", "message": {"content": [{"text": "a"}, {"text": "b"}]}}) == "a b"),
    ]
    for name, ok in cases:
        print("  %-4s %s" % ("PASS" if ok else "FAIL", name))
        bad += 0 if ok else 1
    print("\nRESULT: %s -- %d/%d" % ("PASS" if not bad else "FAIL", len(cases) - bad, len(cases)))
    return 0 if not bad else 1


if __name__ == "__main__":
    sys.exit(main())
