#!/usr/bin/env python3
"""Deploy-parity checker: does ~/.claude/skills/ (deployed) match skills/ (repo)?

THE DEFECT THIS CLOSES (2026-07-26)
------------------------------------
`sync-universal.sh` deploys skills with `cp -r skills/. ~/.claude/skills/` — see that
file, line 29. `cp -r` COPIES; it never DELETES. When commit `4c90cad` renamed
`skills/triage-packet/` to `skills/cross-venue-intake/`, the sync ran, copied the new
directory in alongside the old one, and left `~/.claude/skills/triage-packet/` sitting
there — live, with valid frontmatter, and a trigger description overlapping its own
replacement. Nothing in the pipeline can notice this: the repo has no record of the old
name (git doesn't track deletions in the working tree, only in history), and the
deployed tree has no record of which repo commit it was last synced from. Jon named the
right frame for it: this repo already has a concept for a stale copy that answers as if
it were live — the worktree-echo rule ("multi-hit title search = worktree echo"). A
ghost skill is that same failure mode in the skills layer. **Every rename or deletion of
a skill, ever, has left a ghost** if `sync-universal.sh` ran in between and nobody
manually cleaned the old directory out afterward — this script is the general detector
for that whole class, not just the one instance already found by hand.

GHOSTS ARE LIVE AND AUTO-INVOKABLE — THIS IS WHY GHOST IS THE SERIOUS CLASS
----------------------------------------------------------------------------
A skill directory under `~/.claude/skills/<name>/SKILL.md` with parseable frontmatter is
discoverable and auto-invocable by the platform **purely from the deployed tree** — the
repo is never consulted at session start. `scripts/audit/lint_skills.py`'s own docstring
states the mechanism directly: "A skill's `description:` is what the platform matches
against to decide whether to auto-invoke it" — and that matching runs over whatever is
sitting in `~/.claude/skills/`, full stop. This is not a claim from documentation alone:
the "available skills" listing surfaced in every Claude Code session's system prompt is
generated by scanning the deployed tree, and it lists skills the repo no longer contains
(e.g. `cross-venue-intake` appears; had `triage-packet` not been manually quarantined
minutes before this script was written, it would have appeared too, per Jon's own note in
this brief). A GHOST is therefore not inert leftover disk space — it is a second,
unversioned, ungoverned trigger surface competing with its own replacement for the same
invocations, and nothing short of this detector (or a human noticing by hand, as
happened once already) will ever surface that fact.

THE FOUR CLASSES — KEPT SEPARATE ON PURPOSE
---------------------------------------------
Different causes, different fixes, different urgency. Merging them into one tally would
make the check useless (see `lint_skills.py`'s own CONFIRMED-vs-SPEC precedent for the
same principle):

  GHOST     — skill directory deployed, no counterpart in the repo. Almost always a
              rename or deletion the sync never propagated. SERIOUS: live, auto-invokable,
              ungoverned. Fix requires a human decision to remove it (see below) — this
              script does not do that.
  MISSING   — skill directory in the repo, not deployed. Ordinary mid-work state: a new
              skill not yet synced, or a sync that hasn't run / failed. NOT inherently
              alarming.
  DIVERGED  — present in both, content differs. Compared by SHA-256 content hash of every
              file in the directory tree (including but not limited to SKILL.md) — never
              mtime, never size. This repo has been burned repeatedly by a proxy standing
              in for the thing itself (see the "Derive, Don't Record" and
              "Detection Proxies Lie" memory notes); a hash is the only thing that
              actually answers "is the content the same."
  IN SYNC   — present in both, byte-identical across every file. The healthy case.

A "skill directory" for this script's purposes is a top-level child of a root that
contains a `SKILL.md` file directly inside it (same convention `lint_skills.py` uses via
its `skills/*/SKILL.md` glob). Bare directories with no `SKILL.md` (stray Drive-sync
cruft — an empty `New folder` was found sitting in the live deployed tree during this
script's construction) are not skill constructs at all under the platform's own
discovery rule and are silently excluded from all four classes, not misreported as
GHOST. `--verbose` lists them so they aren't invisible either.

WHY AN EMPTY OR ABSENT ROOT IS A HARD ERROR, NOT A FINDING
-------------------------------------------------------------
A run against a wrong or absent root has already produced one invalid finding in this
program (a run that pointed `--deployed-root` at nothing would silently report every
repo skill as GHOST, and a run that pointed `--repo-root` at nothing would report every
deployed skill as MISSING — the exact inversion of a real finding). Both roots are
checked to exist AND be non-empty before any classification runs; failure to do so aborts
loudly with a distinct exit code, per the same discipline `verify_quotes.py --raw-root`
already enforces in this repo.

WHY --strict DOES NOT FAIL ON MISSING BY DEFAULT
---------------------------------------------------
A repo skill not yet deployed is normal mid-work state — you're mid-edit, or the sync
just hasn't run yet this session. Gating `--strict` on MISSING by default would make it
fail on completely ordinary in-progress work, training the operator to ignore the exit
code — this repo has already built and named that failure mode once (see RATIO_FLOOR in
the "Derive, Don't Record" memory note, and `verify_quotes.py`'s UNRESOLVABLE precedent,
the same shape of decision). GHOST and DIVERGED are different: a ghost is never expected
mid-work state (nothing legitimately deploys a skill the repo doesn't have — deployment
only ever flows repo -> deployed), and a divergence means the deployed tree is running
something the repo review process never saw. Both gate `--strict` by default.
`--strict-missing` exists for whoever wants the harder bar (e.g. a pre-release check that
everything in the repo is actually live).

A GOTCHA FOUND WHILE BUILDING THIS: FRESH-CHECKOUT CRLF IS A FALSE DIVERGED
------------------------------------------------------------------------------
This repo's `.gitattributes` forces LF only for `*.sh` and `*.py`; markdown is left to
whatever `core.autocrlf` says. On a Windows machine with the common `core.autocrlf=true`
default, a **freshly re-checked-out working tree** (e.g. a brand-new worktree, or a fresh
clone) rewrites every committed LF byte in every `SKILL.md` and reference `.md` to CRLF on
checkout. The persistent, long-lived working copy that `sync-universal.sh` actually reads
from was never re-checked-out this way and stays LF, matching the deployed tree exactly.
Point `--repo-root` at a **freshly checked-out** worktree/clone on such a machine and every
single skill will spuriously report DIVERGED — 14 of 33 did, on the exact machine this
script was built on, before this was diagnosed and traced to `core.autocrlf`, not to any
real content change. This script intentionally does NOT paper over that by normalizing
line endings at hash time (byte-fidelity is the whole point — see "Compare by content
hash... not mtime, not size" above); the fix is operational, not code: run `--repo-root`
against the actual persistent working tree the real sync draws from, not a re-checkout of
it, or set `core.autocrlf=false` for the comparison tree first.

GIT-HISTORY ATTRIBUTION FOR GHOSTS
-------------------------------------
For each GHOST, this script runs
`git log --all --diff-filter=DR --name-status -- 'skills/<name>*'` against the repo root
(must be inside a git working tree; the worktree this was built in qualifies) and reports
the most recent commit that deleted or renamed a matching path, plus the rename target
if git detected one. That turns "there is a ghost" into "here is when it was orphaned and
to what" — the difference between a report and a diagnosis. If the repo root is not a git
working tree (e.g. the synthetic self-test fixture), attribution is reported as
unavailable rather than guessed at.

READ-ONLY
---------
This script reports. It does not delete, sync, or repair anything in either root.
Removing a live GHOST from the deployed tree is a judgment call (a skill mid-migration
might legitimately be present only in the deployed tree for a short window) and stays a
human decision — this script's only job is to make sure that decision is never made
blind.

Usage:
  sync_parity.py [--deployed-root ~/.claude/skills] [--repo-root skills]
                  [--strict] [--strict-missing] [--verbose]
  sync_parity.py --self-test
"""
import argparse
import hashlib
import os
import subprocess
import sys

sys.stdout.reconfigure(encoding="utf-8")

GHOST, MISSING, DIVERGED, IN_SYNC = "GHOST", "MISSING", "DIVERGED", "IN SYNC"


# --------------------------------------------------------------------------
# Root validation — fail loudly, never silently treat a bad root as a finding.
# --------------------------------------------------------------------------

def check_root(path, label):
    """Returns None if OK, else an error message string. A root must exist, be a
    directory, and contain at least one entry. An empty root is an ERROR, not a
    (vacuously true) finding of "everything is GHOST/MISSING" — see docstring.
    """
    if not path or not os.path.isdir(path):
        return (f"--{label} '{path}' does not exist or is not a directory.\n"
                f"       A run against a wrong or absent root has already produced one\n"
                f"       invalid finding in this program (everything reported GHOST or\n"
                f"       MISSING when it was really just an absent root). Refusing to run.")
    try:
        entries = os.listdir(path)
    except OSError as e:
        return f"--{label} '{path}' could not be listed: {e}"
    if not entries:
        return (f"--{label} '{path}' exists but is EMPTY.\n"
                f"       An empty root must be an error, never a finding. Refusing to run.")
    return None


# --------------------------------------------------------------------------
# Skill discovery — a "skill directory" is a top-level child containing SKILL.md,
# same convention lint_skills.py uses (skills/*/SKILL.md).
# --------------------------------------------------------------------------

def discover_skill_dirs(root):
    """Returns (skills, ignored) where skills maps name -> full path for every
    top-level child directory of `root` containing a SKILL.md, and `ignored` is
    the sorted list of top-level child directory names that do NOT (stray cruft —
    not a skill construct under the platform's own discovery rule).
    """
    skills, ignored = {}, []
    for name in sorted(os.listdir(root)):
        full = os.path.join(root, name)
        if not os.path.isdir(full):
            continue  # loose files at top level (UPSTREAM.md, roles-overview.md, ...) — not skills
        if os.path.isfile(os.path.join(full, "SKILL.md")):
            skills[name] = full
        else:
            ignored.append(name)
    return skills, ignored


# --------------------------------------------------------------------------
# Content comparison — SHA-256 of every file in the tree. Never mtime, never size.
# --------------------------------------------------------------------------

# Gitignored build/OS artifacts (see .gitignore: __pycache__/, *.pyc, *.pyo, .DS_Store,
# Thumbs.db) — excluded from hashing. Found empirically on the real run: chat-exporter/
# and wiki-master/ both had a live scripts/__pycache__/*.pyc sitting in the checked-out
# working directory (from having actually been executed there), present on one side and
# absent on the other, producing a DIVERGED verdict that was not a real skill-content
# difference. That is exactly the false-alarm-erodes-trust failure this repo has already
# named once (RATIO_FLOOR, "Derive, Don't Record" memory note) — a real GHOST or a real
# content edit must never share a tally with a compiled-bytecode cache file. These are
# never part of what the platform reads as skill content; they are excluded from ALL
# comparison, not merely down-weighted.
IGNORED_DIRNAMES = {"__pycache__"}
IGNORED_FILENAMES = {".DS_Store", "Thumbs.db"}
IGNORED_SUFFIXES = (".pyc", ".pyo")


def hash_tree(directory):
    """rel-posix-path -> sha256 hex digest, for every file under `directory`,
    excluding gitignored build/OS artifacts (see IGNORED_* above)."""
    out = {}
    for dirpath, dirnames, filenames in os.walk(directory):
        dirnames[:] = sorted(d for d in dirnames if d not in IGNORED_DIRNAMES)
        for fn in sorted(filenames):
            if fn in IGNORED_FILENAMES or fn.endswith(IGNORED_SUFFIXES):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, directory).replace(os.sep, "/")
            h = hashlib.sha256()
            try:
                with open(full, "rb") as f:
                    for chunk in iter(lambda: f.read(65536), b""):
                        h.update(chunk)
            except OSError as e:
                out[rel] = f"UNREADABLE:{e}"
                continue
            out[rel] = h.hexdigest()
    return out


def compare_dirs(repo_dir, deployed_dir):
    """Returns a list of human-readable diff strings; empty list means byte-identical
    across every file in the tree (IN SYNC).
    """
    repo_hashes = hash_tree(repo_dir)
    dep_hashes = hash_tree(deployed_dir)
    diffs = []
    only_repo = sorted(set(repo_hashes) - set(dep_hashes))
    only_dep = sorted(set(dep_hashes) - set(repo_hashes))
    changed = sorted(f for f in (set(repo_hashes) & set(dep_hashes))
                      if repo_hashes[f] != dep_hashes[f])
    if only_repo:
        diffs.append(f"file(s) only in repo: {only_repo}")
    if only_dep:
        diffs.append(f"file(s) only in deployed: {only_dep}")
    if changed:
        diffs.append(f"content differs: {changed}")
    return diffs


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------

def classify(repo_root, deployed_root):
    """Returns (results, repo_ignored, dep_ignored).
    results: name -> (verdict, diffs_or_None)
    """
    repo_skills, repo_ignored = discover_skill_dirs(repo_root)
    dep_skills, dep_ignored = discover_skill_dirs(deployed_root)

    results = {}
    for name in sorted(set(repo_skills) | set(dep_skills)):
        in_repo, in_dep = name in repo_skills, name in dep_skills
        if in_repo and in_dep:
            diffs = compare_dirs(repo_skills[name], dep_skills[name])
            results[name] = (DIVERGED if diffs else IN_SYNC, diffs or None)
        elif in_dep:
            results[name] = (GHOST, None)
        else:
            results[name] = (MISSING, None)
    return results, repo_ignored, dep_ignored


# --------------------------------------------------------------------------
# Git-history attribution for GHOSTs
# --------------------------------------------------------------------------

def git_history_for_ghost(repo_root, name):
    """Search git history for the commit that deleted or renamed skills/<name>*.
    Returns a dict: {"available": bool, "reason": str or None, "commit": str or None,
    "date": str or None, "subject": str or None, "event": str or None}.
    Never guesses — if the repo root is not a git working tree, or nothing is found,
    says so plainly rather than fabricating an attribution.
    """
    result = {"available": False, "reason": None, "commit": None, "date": None,
              "subject": None, "event": None}
    pattern = f"skills/{name}*"
    try:
        proc = subprocess.run(
            ["git", "-C", repo_root, "log", "--all", "--diff-filter=DR",
             "--name-status", "--format=COMMIT|%H|%ad|%s", "--date=short", "--", pattern],
            capture_output=True, text=True, timeout=20)
    except FileNotFoundError:
        result["reason"] = "git executable not found on PATH"
        return result
    if proc.returncode != 0:
        result["reason"] = (proc.stderr.strip()[:300]
                             or "git log failed (repo root is likely not a git working tree)")
        return result

    lines = proc.stdout.splitlines()
    blocks = []
    cur_header, cur_body = None, []
    for line in lines:
        if line.startswith("COMMIT|"):
            if cur_header is not None:
                blocks.append((cur_header, cur_body))
            cur_header, cur_body = line, []
        elif line.strip():
            cur_body.append(line)
    if cur_header is not None:
        blocks.append((cur_header, cur_body))

    if not blocks:
        result["available"] = True
        result["reason"] = "no matching delete/rename commit found in history"
        return result

    # Most recent block (git log defaults to reverse-chronological) whose name-status
    # lines actually touch skills/<name>[/...] — the pathspec glob can match near-misses
    # (e.g. skills/<name>-old), so re-confirm against the exact prefix.
    prefix = f"skills/{name}"
    for header, body in blocks:
        _, commit, date, subject = header.split("|", 3)
        for status_line in body:
            parts = status_line.split("\t")
            status = parts[0]
            if status.startswith("R"):
                old_path, new_path = parts[1], parts[2]
                if old_path == prefix or old_path.startswith(prefix + "/"):
                    result.update(available=True, commit=commit, date=date, subject=subject,
                                  event=f"RENAMED to {new_path}")
                    return result
            elif status.startswith("D"):
                old_path = parts[1]
                if old_path == prefix or old_path.startswith(prefix + "/"):
                    result.update(available=True, commit=commit, date=date, subject=subject,
                                  event="DELETED")
                    return result

    result["available"] = True
    result["reason"] = "matching commits found but none touched an exact skills/<name> path"
    return result


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def report(results, repo_ignored, dep_ignored, repo_root, verbose=False):
    tallies = {GHOST: 0, MISSING: 0, DIVERGED: 0, IN_SYNC: 0}
    for _, (verdict, _) in results.items():
        tallies[verdict] += 1

    print(f"=== SYNC PARITY — {len(results)} skill(s) compared ===\n")
    print(f"  GHOST     : {tallies[GHOST]:>3}  <- serious: deployed, live, auto-invokable, "
          f"no repo counterpart")
    print(f"  MISSING   : {tallies[MISSING]:>3}  (in repo, not deployed — normal mid-work state)")
    print(f"  DIVERGED  : {tallies[DIVERGED]:>3}  <- content differs (SHA-256, not mtime/size)")
    print(f"  IN SYNC   : {tallies[IN_SYNC]:>3}  (byte-identical)")

    ghosts = sorted(n for n, (v, _) in results.items() if v == GHOST)
    if ghosts:
        print(f"\n-- GHOST ({len(ghosts)}) — deployed with no repo counterpart --")
        for name in ghosts:
            hist = git_history_for_ghost(repo_root, name)
            print(f"  {name}")
            if hist["event"]:
                print(f"      orphaned by {hist['commit'][:10]} ({hist['date']}) {hist['event']}"
                      f" — \"{hist['subject']}\"")
            else:
                print(f"      git-history attribution: {hist['reason']}")

    diverged = sorted(n for n, (v, _) in results.items() if v == DIVERGED)
    if diverged:
        print(f"\n-- DIVERGED ({len(diverged)}) — present both places, content differs --")
        for name in diverged:
            _, diffs = results[name]
            print(f"  {name}")
            for d in diffs:
                print(f"      {d}")

    missing = sorted(n for n, (v, _) in results.items() if v == MISSING)
    if missing:
        print(f"\n-- MISSING ({len(missing)}) — in repo, not deployed --")
        for name in missing:
            print(f"  {name}")

    if verbose:
        in_sync = sorted(n for n, (v, _) in results.items() if v == IN_SYNC)
        if in_sync:
            print(f"\n-- IN SYNC ({len(in_sync)}) --")
            for name in in_sync:
                print(f"  {name}")
        if repo_ignored:
            print(f"\n-- ignored top-level repo/ entries with no SKILL.md ({len(repo_ignored)}) --")
            for name in repo_ignored:
                print(f"  {name}")
        if dep_ignored:
            print(f"\n-- ignored top-level deployed entries with no SKILL.md ({len(dep_ignored)}) --")
            for name in dep_ignored:
                print(f"  {name}")

    print()
    return tallies


# --------------------------------------------------------------------------
# Self-test — a detector that has never seen the thing it detects has not been tested.
# --------------------------------------------------------------------------

def _write(root, rel, content):
    p = os.path.join(root, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    return p


def self_test():
    import tempfile
    tmp = tempfile.mkdtemp()
    repo_root = os.path.join(tmp, "repo_skills")
    dep_root = os.path.join(tmp, "deployed_skills")

    # GHOST: deployed only.
    _write(dep_root, "ghost-skill/SKILL.md", "---\nname: ghost-skill\ndescription: a ghost\n---\nbody\n")

    # MISSING: repo only.
    _write(repo_root, "missing-skill/SKILL.md",
           "---\nname: missing-skill\ndescription: not yet deployed\n---\nbody\n")

    # DIVERGED: present both places, content differs.
    _write(repo_root, "diverged-skill/SKILL.md",
           "---\nname: diverged-skill\ndescription: v2\n---\nbody v2\n")
    _write(dep_root, "diverged-skill/SKILL.md",
           "---\nname: diverged-skill\ndescription: v1 (stale)\n---\nbody v1\n")

    # IN SYNC: byte-identical, including a nested reference file (exercise the "every
    # file in the directory" requirement, not just SKILL.md).
    same_skill_md = "---\nname: in-sync-skill\ndescription: identical\n---\nbody\n"
    _write(repo_root, "in-sync-skill/SKILL.md", same_skill_md)
    _write(dep_root, "in-sync-skill/SKILL.md", same_skill_md)
    same_ref = "reference content, unchanged\n"
    _write(repo_root, "in-sync-skill/references/notes.md", same_ref)
    _write(dep_root, "in-sync-skill/references/notes.md", same_ref)

    # Non-skill cruft (no SKILL.md) present in both roots — must be IGNORED, not
    # misreported as GHOST/MISSING (regression guard for the "New folder" finding).
    os.makedirs(os.path.join(dep_root, "New folder"), exist_ok=True)
    os.makedirs(os.path.join(repo_root, "stray-empty-dir"), exist_ok=True)

    failures = []

    # --- root validation: empty and absent roots must error, not classify ---
    err = check_root(os.path.join(tmp, "does-not-exist"), "deployed-root")
    if err is None:
        failures.append("check_root: absent root should return an error, returned None")
    empty_root = os.path.join(tmp, "empty_root")
    os.makedirs(empty_root)
    err = check_root(empty_root, "deployed-root")
    if err is None:
        failures.append("check_root: empty root should return an error, returned None")
    err = check_root(repo_root, "repo-root")
    if err is not None:
        failures.append(f"check_root: valid non-empty root should return None, got: {err}")

    # --- classification ---
    results, repo_ignored, dep_ignored = classify(repo_root, dep_root)

    expected = {
        "ghost-skill": GHOST,
        "missing-skill": MISSING,
        "diverged-skill": DIVERGED,
        "in-sync-skill": IN_SYNC,
    }
    for name, want in expected.items():
        got = results.get(name, (None, None))[0]
        if got != want:
            failures.append(f"{name}: expected {want}, got {got}")

    if "New folder" in results or "New folder" in results.values():
        failures.append("'New folder' (no SKILL.md) leaked into classified results")
    if "New folder" not in dep_ignored:
        failures.append("'New folder' should have been recorded as an ignored non-skill entry")
    if "stray-empty-dir" not in repo_ignored:
        failures.append("'stray-empty-dir' should have been recorded as an ignored non-skill entry")

    # --- diverged diff detail sanity ---
    _, diffs = results["diverged-skill"]
    if not diffs or not any("content differs" in d for d in diffs):
        failures.append(f"diverged-skill: expected a 'content differs' diff entry, got {diffs}")

    # --- git-history attribution on a non-git repo root must degrade honestly, never crash ---
    hist = git_history_for_ghost(repo_root, "ghost-skill")
    if hist["available"] and hist["event"] is not None:
        failures.append("git_history_for_ghost: fabricated an attribution against a non-git root")
    if hist["reason"] is None:
        failures.append("git_history_for_ghost: should explain why attribution is unavailable")

    if failures:
        print(f"SELF-TEST: {len(failures)} FAILURE(S)")
        for f_ in failures:
            print(f"  FAIL: {f_}")
        return 1
    print("SELF-TEST: all cases passed "
          "(GHOST/MISSING/DIVERGED/IN SYNC all correctly classified; non-skill cruft "
          "correctly ignored in both roots; empty/absent root correctly rejected; "
          "git-history attribution degrades honestly on a non-git root)")
    return 0


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--deployed-root", default=os.path.expanduser("~/.claude/skills"),
                    help="the deployed tree Claude Code actually reads (default: ~/.claude/skills)")
    ap.add_argument("--repo-root", default="skills",
                    help="the repo's source-of-truth skills/ directory (default: skills)")
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 if any GHOST or DIVERGED is found.")
    ap.add_argument("--strict-missing", action="store_true",
                    help="ALSO exit 1 if any MISSING is found. Off by default — a repo skill "
                         "not yet deployed is normal mid-work state; see docstring.")
    ap.add_argument("--verbose", action="store_true",
                    help="also list IN SYNC skills and ignored non-skill directories.")
    ap.add_argument("--self-test", action="store_true", dest="self_test")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    dep_err = check_root(args.deployed_root, "deployed-root")
    if dep_err:
        print(f"ERROR: {dep_err}", file=sys.stderr)
        return 2
    repo_err = check_root(args.repo_root, "repo-root")
    if repo_err:
        print(f"ERROR: {repo_err}", file=sys.stderr)
        return 3

    results, repo_ignored, dep_ignored = classify(args.repo_root, args.deployed_root)
    tallies = report(results, repo_ignored, dep_ignored, args.repo_root, verbose=args.verbose)

    if args.strict and (tallies[GHOST] > 0 or tallies[DIVERGED] > 0):
        return 1
    if args.strict_missing and tallies[MISSING] > 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
